version: '4.0'
services:
  postgres:
    image: postgres:13
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Goku*2312
      POSTGRES_DB: ineuron

  app:
    depends_on:
      - postgres
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Goku*2312
      POSTGRES_DB: ineuron
      POSTGRES_HOST: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    stdin_open: true
    tty: true

volumes:
  postgres: